tree_names <- c("covid_edited.rooted.tree", 
		#"nextstrain_ncov_gisaid_global_all-time_timetree.nwk", 
		#"flu_seasonal_h1n1pdm_ha_2y_timetree.nwk", 
		#"nextstrain_rsv_a_genome_timetree.nwk", 
		#"flu_seasonal_h3n2_ha_2y_timetree.nwk", 
		#"nextstrain_seasonal-flu_h3n2_ha_12y_timetree.nwk", 
		#"nextstrain_avian-flu_h9n2_ha_all-time_timetree.nwk", 
		"sequences_rsv_a_treeseq_al_ed.rooted.tree", 
		#"nextstrain_measles_genome_timetree.nwk", 
		"sequences_rsv_b_treeseq_al_ed.rooted.tree")
for (tree_name in tree_names) {
	print(tree_name)
	tree <- ape::read.tree(paste("data/virus/trees/rooted/", tree_name, sep=""))
	results <- c()
	names <- c()
	results <- c(results, treebalance::areaPerPairI(tree))
	names <- c(names, "area_per_pair_index")
	results <- c(results, treebalance::avgLeafDepI(tree))
	names <- c(names, "average_leaf_depth")
	results <- c(results, treebalance::avgVertDep(tree))
	names <- c(names, "average_vertex_depth")
	results <- c(results, treebalance::B1I(tree))
	names <- c(names, "B_1_index")
	results <-c(results, treebalance::B2I(tree))
	names <- c(names, "B_2_index")
	results <- c(results, treebalance::cherryI(tree))
	names <- c(names, "cherry_index")
	results <- c(results, treebalance::collessI(tree, method="original"))
	names <- c(names, "colless_index")
	results <- c(results, treebalance::collessI(tree, method="corrected"))
	names <- c(names, "corrected_colless_index")
	results <- c(results, treebalance::collessI(tree, method="quadratic"))
	names <- c(names, "quadratic_colless_index")
	#results <- c(results, treebalance::colPlaLab(tree))
	#names <- c(names, "colijn_plazotte_rank")
	results <- c(results, treebalance::ewCollessI(tree))
	names <- c(names, "I_2_index")
	#results <- c(results, treebalance::furnasI(tree))
	#names <- c(names, "furnas_rank")
	results <- c(results, treebalance::IbasedI(tree, method="mean"))
	names <- c(names, "mean_I")
	results <- c(results, treebalance::IbasedI(tree, method="total"))
	names <- c(names, "total_I")
	results <- c(results, treebalance::IbasedI(tree, method="mean", correction="prime"))
	names <- c(names, "mean_I_prime")
	results <- c(results, treebalance::IbasedI(tree, method="total", correction="prime"))
	names <- c(names, "total_I_prime")
	results <- c(results, treebalance::IbasedI(tree, method="mean", correction="w"))
	names <- c(names, "mean_I_w")
	results <- c(results, treebalance::IbasedI(tree, method="total", correction="w"))
	names <- c(names, "total_I_w")
	results <- c(results, treebalance::maxDelW(tree, method="original"))
	names <- c(names, "maxdiff_widths")
	results <- c(results, treebalance::maxDelW(tree, method="modified"))
	names <- c(names, "modified_maxdiff_widths")
	results <- c(results, treebalance::maxDepth(tree))
	names <- c(names, "maximum_depth")
	results <- c(results, treebalance::maxWidth(tree))
	names <- c(names, "maximum_width")
	results <- c(results, treebalance::mCherryI(tree))
	names <- c(names, "modified_cherry_index")
	results <- c(results, treebalance::mWovermD(tree))
	names <- c(names, "max_width_over_max_depth")
	results <- c(results, treebalance::rogersI(tree))
	names <- c(names, "rogers_j_index")
	results <- c(results, treebalance::rQuartetI(tree))
	names <- c(names, "rooted_quartet_index")
	results <- c(results, treebalance::sackinI(tree))
	names <- c(names, "sackin_index")
	results <- c(results, treebalance::sShapeI(tree))
	names <- c(names, "s_shape")
	results <- c(results, treebalance::stairs1(tree))
	names <- c(names, "stairs1")
	results <- c(results, treebalance::stairs2(tree))
	names <- c(names, "stairs2")
	results <- c(results, treebalance::symNodesI(tree))
	names <- c(names, "symmetry_nodes_index")
	results <- c(results, treebalance::totCophI(tree))
	names <- c(names, "total_cophenetic_index")
	results <- c(results, treebalance::totIntPathLen(tree))
	names <- c(names, "total_internal_path_length")
	results <- c(results, treebalance::totPathLen(tree))
	names <- c(names, "total_path_length")
	results <- c(results, treebalance::varLeafDepI(tree))
	names <- c(names, "variance_of_leaves_depths")
	results <- c(results, treebalance::weighL1dist(tree))
	names <- c(names, "d_index")
	data <- data.frame(names,results)
	write.csv(data,	paste("data/reference_results/", tree_name, ".csv", sep=""))
}
