
tree <- ape::read.tree("data/virus/trees/rooted/covid_edited.rooted.tree")
start.time <- Sys.time()
treestats::area_per_pair(tree)
treestats::average_leaf_depth(tree)
treestats::avg_ladder(tree)
treestats::avg_vert_depth(tree)
treestats::b1(tree)
treestats::b2(tree)
treestats::blum(tree)
treestats::cherries(tree)
treestats::colless(tree)
treestats::colless_corr(tree)
treestats::colless_quad(tree)
treestats::diameter(tree)
treestats::ew_colless(tree)
treestats::mean_i(tree)
treestats::j_one(tree)
#treestats::j_stat(tree)
treestats::max_del_width(tree)
treestats::max_depth(tree)
treestats::max_ladder(tree)
treestats::max_width(tree)
#treestats::mean_branch_length(tree)
#treestats::mean_branch_length_ext(tree)
#treestats::mean_branch_length_int(tree)
treestats::mntd(tree)
treestats::mean_pair_dist(tree)
treestats::mw_over_md(tree)
treestats::phylogenetic_diversity(tree)
treestats::rogers(tree)
treestats::root_imbalance(tree)
treestats::rquartet(tree)
treestats::sackin(tree)
treestats::stairs(tree)
treestats::stairs2(tree)
treestats::sym_nodes(tree)
treestats::tot_coph(tree)
treestats::tot_internal_path(tree)
treestats::tot_path_length(tree)
treestats::treeness(tree)
#treestats::var_branch_length(tree)
#treestats::var_branch_length_ext(tree)
#treestats::var_branch_length_int(tree)
treestats::var_leaf_depth(tree)
#treestats::vpd(tree)
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
